---
- hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Unarchive wordpress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
        owner: codio
        group: www-data
        extra_opts: [--strip-components=1]

    - name: Update Config  
      template:  
        src: wp-config.php.j2  
        dest: /var/www/html/wp-config.php

    - name: Change file ownership, group, and permissions
      ansible.builtin.file:
        path: /var/www/html
        owner: codio
        group: www-data
        mode: u=rwX,g=rwX,o=rX 
        recurse: true
        state: directory

    - name: Remove old index
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Enable .htaccess files in Apache config
      ansible.builtin.replace:
        path: /etc/apache2/apache2.conf
        after: '<Directory /var/www/>'
        before: '</Directory>'
        regexp: 'AllowOverride None'
        replace: |
          AllowOverride All
          RequestHeader set X-Forwarded-Proto "https"
          RequestHeader set X-Forwarded-Port "443"
      notify:
        - restart apache2

    - name: Enable port 3000
      ansible.builtin.replace:
        path: /etc/apache2/ports.conf 
        regexp: 'Listen 80'
        replace: Listen 3000
      notify:
        - restart apache2

  roles:
    - role: wordpress 
    - role: geerlingguy.mysql
